import type { Recipe } from './types';

const ing = (match: string, label = match, optional = false) => ({ match, label, optional });

/**
 * Starter recipe library. Macros are per serving and approximate
 * (computed from USDA values for the listed amounts).
 */
export const RECIPES: Recipe[] = [
  {
    id: 'chicken-stir-fry',
    name: 'Chicken & Veggie Stir-Fry',
    servings: 3,
    minutes: 25,
    ingredients: [
      ing('chicken', '1 lb chicken breast'),
      ing('broccoli', '2 cups broccoli'),
      ing('pepper', '1 bell pepper'),
      ing('rice', '1 cup rice'),
      ing('soy sauce', '3 tbsp soy sauce'),
      ing('garlic', '2 cloves garlic', true),
      ing('onion', '1 onion', true),
    ],
    steps: [
      'Cook rice.',
      'Slice chicken, sear in a hot oiled pan 5–6 min until cooked through; set aside.',
      'Stir-fry vegetables 4 min, return chicken, add soy sauce and garlic, toss 1 min.',
      'Serve over rice.',
    ],
    macrosPerServing: { calories: 480, protein: 40, carbs: 55, fat: 9 },
  },
  {
    id: 'veggie-omelette',
    name: 'Veggie Omelette',
    servings: 1,
    minutes: 10,
    ingredients: [
      ing('egg', '3 eggs'),
      ing('spinach', '1 handful spinach', true),
      ing('pepper', '1/4 bell pepper', true),
      ing('cheese', '1/4 cup cheese', true),
      ing('onion', '2 tbsp onion', true),
      ing('mushroom', 'mushrooms', true),
    ],
    steps: ['Whisk eggs with salt.', 'Sauté vegetables 2 min.', 'Pour in eggs, cook until set, add cheese, fold.'],
    macrosPerServing: { calories: 330, protein: 24, carbs: 5, fat: 23 },
  },
  {
    id: 'greek-yogurt-bowl',
    name: 'Greek Yogurt Berry Bowl',
    servings: 1,
    minutes: 3,
    ingredients: [ing('yogurt', '1 cup Greek yogurt'), ing('berry|berries|strawberry|strawberries|blueberry|blueberries|raspberry|raspberries|blackberry|blackberries', '1/2 cup berries'), ing('granola', '1/4 cup granola', true), ing('honey', '1 tsp honey', true)],
    steps: ['Layer yogurt, berries, and granola. Drizzle with honey.'],
    macrosPerServing: { calories: 310, protein: 24, carbs: 38, fat: 7 },
  },
  {
    id: 'turkey-chili',
    name: 'Turkey & Bean Chili',
    servings: 6,
    minutes: 45,
    ingredients: [
      ing('ground turkey', '1 lb ground turkey'),
      ing('bean', '2 cans beans'),
      ing('tomato', '1 can crushed tomatoes'),
      ing('onion', '1 onion'),
      ing('pepper', '1 bell pepper', true),
      ing('garlic', '3 cloves garlic', true),
    ],
    steps: ['Brown turkey with onion and pepper.', 'Add garlic, chili powder, cumin, 1 min.', 'Add tomatoes and beans; simmer 30 min.'],
    macrosPerServing: { calories: 340, protein: 27, carbs: 32, fat: 11 },
  },
  {
    id: 'salmon-sheet-pan',
    name: 'Sheet-Pan Salmon & Veg',
    servings: 2,
    minutes: 25,
    ingredients: [
      ing('salmon', '2 salmon fillets'),
      ing('asparagus', '1 bunch asparagus'),
      ing('potato', '2 small potatoes', true),
      ing('lemon', '1 lemon', true),
    ],
    steps: ['Heat oven to 425°F.', 'Roast cubed potatoes 10 min.', 'Add salmon and asparagus, oil, salt, lemon; roast 12 min more.'],
    macrosPerServing: { calories: 520, protein: 38, carbs: 30, fat: 26 },
  },
  {
    id: 'pasta-marinara',
    name: 'Pasta Marinara with Spinach',
    servings: 4,
    minutes: 20,
    ingredients: [
      ing('pasta', '1 lb pasta'),
      ing('marinara', '1 jar marinara'),
      ing('spinach', '4 cups spinach', true),
      ing('parmesan', 'parmesan', true),
      ing('garlic', '2 cloves garlic', true),
    ],
    steps: ['Boil pasta.', 'Warm sauce with garlic, wilt in spinach.', 'Toss with pasta and parmesan.'],
    macrosPerServing: { calories: 510, protein: 17, carbs: 95, fat: 7 },
  },
  {
    id: 'beef-tacos',
    name: 'Ground Beef Tacos',
    servings: 4,
    minutes: 20,
    ingredients: [
      ing('ground beef', '1 lb ground beef'),
      ing('tortilla', '8 tortillas'),
      ing('lettuce', 'shredded lettuce', true),
      ing('tomato', '1 tomato', true),
      ing('cheese', 'shredded cheese', true),
      ing('avocado', '1 avocado', true),
    ],
    steps: ['Brown beef with taco seasoning and a splash of water.', 'Warm tortillas.', 'Fill with beef and toppings.'],
    macrosPerServing: { calories: 520, protein: 28, carbs: 32, fat: 30 },
  },
  {
    id: 'tofu-curry',
    name: 'Coconut Tofu Curry',
    servings: 4,
    minutes: 30,
    ingredients: [
      ing('tofu', '1 block tofu'),
      ing('coconut milk', '1 can coconut milk'),
      ing('curry', '2 tbsp curry paste'),
      ing('rice', '1.5 cups rice'),
      ing('spinach', 'spinach', true),
      ing('pepper', '1 bell pepper', true),
    ],
    steps: ['Cook rice.', 'Pan-fry cubed tofu until golden.', 'Simmer curry paste, coconut milk, vegetables 10 min; add tofu.'],
    macrosPerServing: { calories: 540, protein: 18, carbs: 58, fat: 27 },
  },
  {
    id: 'banana-oat-pancakes',
    name: 'Banana Oat Pancakes',
    servings: 2,
    minutes: 15,
    ingredients: [ing('banana', '2 ripe bananas'), ing('egg', '2 eggs'), ing('oat', '1 cup oats'), ing('milk', '1/4 cup milk', true)],
    steps: ['Blend everything smooth.', 'Cook small pancakes on a greased pan, 2 min per side.'],
    macrosPerServing: { calories: 330, protein: 13, carbs: 52, fat: 8 },
  },
  {
    id: 'chicken-caesar-wrap',
    name: 'Chicken Caesar Wrap',
    servings: 2,
    minutes: 15,
    ingredients: [
      ing('chicken', '8 oz cooked chicken'),
      ing('lettuce', 'romaine lettuce'),
      ing('tortilla', '2 large tortillas'),
      ing('parmesan', 'parmesan', true),
      ing('caesar', 'Caesar dressing', true),
    ],
    steps: ['Chop lettuce, toss with dressing and parmesan.', 'Add sliced chicken, wrap in tortillas.'],
    macrosPerServing: { calories: 470, protein: 38, carbs: 33, fat: 20 },
  },
  {
    id: 'lentil-soup',
    name: 'Lentil Vegetable Soup',
    servings: 6,
    minutes: 45,
    ingredients: [
      ing('lentil', '1.5 cups lentils'),
      ing('carrot', '2 carrots'),
      ing('celery', '2 stalks celery'),
      ing('onion', '1 onion'),
      ing('tomato', '1 can diced tomatoes', true),
      ing('broth', '6 cups broth', true),
    ],
    steps: ['Sauté onion, carrot, celery 6 min.', 'Add lentils, tomatoes, broth; simmer 30 min.', 'Season with salt and lemon.'],
    macrosPerServing: { calories: 250, protein: 15, carbs: 42, fat: 3 },
  },
  {
    id: 'fried-rice',
    name: 'Clean-Out-the-Fridge Fried Rice',
    servings: 3,
    minutes: 20,
    ingredients: [
      ing('rice', '3 cups cooked rice'),
      ing('egg', '3 eggs'),
      ing('soy sauce', 'soy sauce'),
      ing('pea', 'peas', true),
      ing('carrot', 'carrot', true),
      ing('onion', 'green onion', true),
      ing('chicken', 'leftover chicken', true),
    ],
    steps: ['Scramble eggs, set aside.', 'Stir-fry vegetables 3 min, add rice, fry 4 min.', 'Add eggs, protein, soy sauce.'],
    macrosPerServing: { calories: 430, protein: 18, carbs: 62, fat: 11 },
  },
  {
    id: 'caprese-salad',
    name: 'Caprese Salad',
    servings: 2,
    minutes: 10,
    ingredients: [ing('tomato', '3 tomatoes'), ing('mozzarella', '8 oz fresh mozzarella'), ing('basil', 'fresh basil', true), ing('balsamic', 'balsamic', true)],
    steps: ['Slice tomatoes and mozzarella.', 'Layer with basil, drizzle with olive oil and balsamic, salt.'],
    macrosPerServing: { calories: 380, protein: 22, carbs: 10, fat: 28 },
  },
  {
    id: 'steak-potatoes',
    name: 'Steak with Roasted Potatoes',
    servings: 2,
    minutes: 40,
    ingredients: [ing('steak', '1 lb steak'), ing('potato', '1 lb potatoes'), ing('green bean', 'green beans', true), ing('butter', 'butter', true)],
    steps: ['Roast potatoes at 425°F 30 min.', 'Sear steak 4 min per side, rest 5 min.', 'Sauté green beans in butter.'],
    macrosPerServing: { calories: 690, protein: 50, carbs: 40, fat: 35 },
  },
  {
    id: 'smoothie',
    name: 'Protein Fruit Smoothie',
    servings: 1,
    minutes: 5,
    ingredients: [ing('banana', '1 banana'), ing('milk', '1 cup milk'), ing('berry|berries|strawberry|strawberries|blueberry|blueberries|raspberry|raspberries|blackberry|blackberries', '1/2 cup berries', true), ing('yogurt', '1/2 cup yogurt', true), ing('spinach', 'handful spinach', true)],
    steps: ['Blend until smooth.'],
    macrosPerServing: { calories: 340, protein: 18, carbs: 55, fat: 6 },
  },
  {
    id: 'shrimp-garlic-pasta',
    name: 'Garlic Butter Shrimp Pasta',
    servings: 3,
    minutes: 20,
    ingredients: [ing('shrimp', '1 lb shrimp'), ing('pasta', '8 oz pasta'), ing('garlic', '4 cloves garlic'), ing('butter', '3 tbsp butter'), ing('lemon', '1 lemon', true), ing('parmesan', 'parmesan', true)],
    steps: ['Boil pasta.', 'Melt butter, cook garlic 30 s, add shrimp 3 min.', 'Toss with pasta, lemon, parmesan.'],
    macrosPerServing: { calories: 560, protein: 38, carbs: 60, fat: 17 },
  },
];
